/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as coreRouteRouteImport } from './routes/(core)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as coreIndexRouteImport } from './routes/(core)/index'
import { Route as coreTransactionsRouteImport } from './routes/(core)/transactions'
import { Route as coreSettingsRouteImport } from './routes/(core)/settings'
import { Route as coreReportsRouteImport } from './routes/(core)/reports'
import { Route as coreProjectsRouteImport } from './routes/(core)/projects'
import { Route as coreBudgetsRouteImport } from './routes/(core)/budgets'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const coreRouteRoute = coreRouteRouteImport.update({
  id: '/(core)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const coreIndexRoute = coreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreTransactionsRoute = coreTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreSettingsRoute = coreSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreReportsRoute = coreReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreProjectsRoute = coreProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreBudgetsRoute = coreBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => coreRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/budgets': typeof coreBudgetsRoute
  '/projects': typeof coreProjectsRoute
  '/reports': typeof coreReportsRoute
  '/settings': typeof coreSettingsRoute
  '/transactions': typeof coreTransactionsRoute
  '/': typeof coreIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/budgets': typeof coreBudgetsRoute
  '/projects': typeof coreProjectsRoute
  '/reports': typeof coreReportsRoute
  '/settings': typeof coreSettingsRoute
  '/transactions': typeof coreTransactionsRoute
  '/': typeof coreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(core)': typeof coreRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(core)/budgets': typeof coreBudgetsRoute
  '/(core)/projects': typeof coreProjectsRoute
  '/(core)/reports': typeof coreReportsRoute
  '/(core)/settings': typeof coreSettingsRoute
  '/(core)/transactions': typeof coreTransactionsRoute
  '/(core)/': typeof coreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/budgets'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/budgets'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/'
  id:
    | '__root__'
    | '/(auth)'
    | '/(core)'
    | '/(auth)/login'
    | '/(core)/budgets'
    | '/(core)/projects'
    | '/(core)/reports'
    | '/(core)/settings'
    | '/(core)/transactions'
    | '/(core)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  coreRouteRoute: typeof coreRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(core)': {
      id: '/(core)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof coreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/': {
      id: '/(core)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof coreIndexRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/transactions': {
      id: '/(core)/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof coreTransactionsRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/settings': {
      id: '/(core)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof coreSettingsRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/reports': {
      id: '/(core)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof coreReportsRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/projects': {
      id: '/(core)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof coreProjectsRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/budgets': {
      id: '/(core)/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof coreBudgetsRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface coreRouteRouteChildren {
  coreBudgetsRoute: typeof coreBudgetsRoute
  coreProjectsRoute: typeof coreProjectsRoute
  coreReportsRoute: typeof coreReportsRoute
  coreSettingsRoute: typeof coreSettingsRoute
  coreTransactionsRoute: typeof coreTransactionsRoute
  coreIndexRoute: typeof coreIndexRoute
}

const coreRouteRouteChildren: coreRouteRouteChildren = {
  coreBudgetsRoute: coreBudgetsRoute,
  coreProjectsRoute: coreProjectsRoute,
  coreReportsRoute: coreReportsRoute,
  coreSettingsRoute: coreSettingsRoute,
  coreTransactionsRoute: coreTransactionsRoute,
  coreIndexRoute: coreIndexRoute,
}

const coreRouteRouteWithChildren = coreRouteRoute._addFileChildren(
  coreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  coreRouteRoute: coreRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
