/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as coreRouteRouteImport } from './routes/(core)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as coreIndexRouteImport } from './routes/(core)/index'
import { Route as coreSettingsRouteImport } from './routes/(core)/settings'
import { Route as coreProjectsRouteImport } from './routes/(core)/projects'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const coreRouteRoute = coreRouteRouteImport.update({
  id: '/(core)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const coreIndexRoute = coreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreSettingsRoute = coreSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreProjectsRoute = coreProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => coreRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/projects': typeof coreProjectsRoute
  '/settings': typeof coreSettingsRoute
  '/': typeof coreIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/projects': typeof coreProjectsRoute
  '/settings': typeof coreSettingsRoute
  '/': typeof coreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(core)': typeof coreRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(core)/projects': typeof coreProjectsRoute
  '/(core)/settings': typeof coreSettingsRoute
  '/(core)/': typeof coreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/projects' | '/settings' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/projects' | '/settings' | '/'
  id:
    | '__root__'
    | '/(auth)'
    | '/(core)'
    | '/(auth)/login'
    | '/(core)/projects'
    | '/(core)/settings'
    | '/(core)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  coreRouteRoute: typeof coreRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(core)': {
      id: '/(core)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof coreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/': {
      id: '/(core)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof coreIndexRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/settings': {
      id: '/(core)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof coreSettingsRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/projects': {
      id: '/(core)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof coreProjectsRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface coreRouteRouteChildren {
  coreProjectsRoute: typeof coreProjectsRoute
  coreSettingsRoute: typeof coreSettingsRoute
  coreIndexRoute: typeof coreIndexRoute
}

const coreRouteRouteChildren: coreRouteRouteChildren = {
  coreProjectsRoute: coreProjectsRoute,
  coreSettingsRoute: coreSettingsRoute,
  coreIndexRoute: coreIndexRoute,
}

const coreRouteRouteWithChildren = coreRouteRoute._addFileChildren(
  coreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  coreRouteRoute: coreRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
